# Customer_Churn

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import matplotlib

WARNING:tensorflow:From C:\Users\Vikrant Chauhan\anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
df=pd.read_csv('./customer_churn.csv')

In [3]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
df.drop(['customerID'],axis=1,inplace=True)

In [5]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [6]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [7]:
# pd.to_numeric(df['TotalCharges'])
# need to remove the null values
pd.to_numeric(df['TotalCharges'],errors='coerce')

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [8]:
pd.to_numeric(df['TotalCharges'],errors='coerce').isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: TotalCharges, Length: 7043, dtype: bool

In [9]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [10]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
df[pd.to_numeric(df["TotalCharges"],errors='coerce').isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [12]:
df[pd.to_numeric(df["TotalCharges"],errors='coerce').isnull()].shape

(11, 20)

In [13]:
df.iloc[488]

gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges
Churn                                      No
Name: 488, dtype: object

In [14]:
df.iloc[488].TotalCharges

' '

In [15]:
df=df[df.TotalCharges!=' ']

In [16]:
df.shape

(7032, 20)

In [17]:
df[pd.to_numeric(df.TotalCharges).isnull()]

Empty DataFrame
Columns: [gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

Main Step To Change The Data Types

In [18]:
df.TotalCharges=pd.to_numeric(df.TotalCharges)

C:\Users\Vikrant Chauhan\AppData\Local\Temp\ipykernel_19040\680514069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.TotalCharges=pd.to_numeric(df.TotalCharges)

In [19]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [20]:
for columns in df:
    print('{} {}'.format(columns,df[columns].unique()))

gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService ['No' 'Yes']
MultipleLines ['No phone service' 'No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn ['No' 'Yes']

In [21]:
columns_to_replace = ['OnlineSecurity', 'OnlineBackup']
df[columns_to_replace].replace('No internet service','No',inplace=True)

C:\Users\Vikrant Chauhan\AppData\Local\Temp\ipykernel_19040\3484512727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[columns_to_replace].replace('No internet service','No',inplace=True)

In [22]:
for columns in df:
    print('{} {}'.format(columns,df[columns].unique()))

gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService ['No' 'Yes']
MultipleLines ['No phone service' 'No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn ['No' 'Yes']

In [23]:
df.replace({'No internet service':'No','No phone service':'No'},inplace=True)

C:\Users\Vikrant Chauhan\AppData\Local\Temp\ipykernel_19040\3104601704.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace({'No internet service':'No','No phone service':'No'},inplace=True)

In [24]:
for columns in df:
    print('{} {}'.format(columns,df[columns].unique()))

gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService ['No' 'Yes']
MultipleLines ['No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes']
OnlineBackup ['Yes' 'No']
DeviceProtection ['No' 'Yes']
TechSupport ['No' 'Yes']
StreamingTV ['No' 'Yes']
StreamingMovies ['No' 'Yes']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn ['No' 'Yes']

In [25]:
# df.replace({'No':0,'Yes':1},inplace=True)
# wrong way beacue it changes the value of other in which we need the no

In [26]:
yes_no_columns = ['Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup',
                  'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']
for col in yes_no_columns:
    df[col].replace({'Yes': 1,'No': 0},inplace=True)

C:\Users\Vikrant Chauhan\AppData\Local\Temp\ipykernel_19040\2444924067.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col].replace({'Yes': 1,'No': 0},inplace=True)

In [27]:
for columns in df:
    print('{} {}'.format(columns,df[columns].unique()))

gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner [1 0]
Dependents [0 1]
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService [0 1]
MultipleLines [0 1]
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity [0 1]
OnlineBackup [1 0]
DeviceProtection [0 1]
TechSupport [0 1]
StreamingTV [0 1]
StreamingMovies [0 1]
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling [1 0]
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn [0 1]

One Hot Encoding

In [28]:
df=pd.get_dummies(data=df,columns=['InternetService','Contract','PaymentMethod'])

In [29]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,Female,0,1,0,1,0,0,0,1,0,...,1,0,0,1,0,0,0,0,1,0
1,Male,0,0,0,34,1,0,1,0,1,...,1,0,0,0,1,0,0,0,0,1
2,Male,0,0,0,2,1,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
3,Male,0,0,0,45,0,0,1,0,1,...,1,0,0,0,1,0,1,0,0,0
4,Female,0,0,0,2,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,1,1,24,1,1,1,0,1,...,1,0,0,0,1,0,0,0,0,1
7039,Female,0,1,1,72,1,1,0,1,1,...,0,1,0,0,1,0,0,1,0,0
7040,Female,0,1,1,11,0,0,1,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,Male,1,1,0,4,1,1,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,Male,0,0,0,66,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,0

In [30]:
df.dtypes

gender                                      object
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
Contract_Month-to-month                      uint8
Contract_One year                            uint8
Contract_Two year                            uint8
PaymentMethod_Bank transfer (automatic)      uint8
PaymentMethod_Credit card (automatic)        uint8
PaymentMethod_Electronic check               uint8
PaymentMethod_Mailed check                   uint8
dtype: object

In [31]:
df['gender'].replace({'Female':1,'Male':0},inplace=True)

In [32]:
df.dtypes

gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
Contract_Month-to-month                      uint8
Contract_One year                            uint8
Contract_Two year                            uint8
PaymentMethod_Bank transfer (automatic)      uint8
PaymentMethod_Credit card (automatic)        uint8
PaymentMethod_Electronic check               uint8
PaymentMethod_Mailed check                   uint8
dtype: object

In [33]:
X=df.drop(['Churn'],axis=1)
y=df.Churn

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [35]:
y.shape

(7032,)

In [36]:
y_train.shape

(5625,)

In [37]:
y_train

5664    1
101     0
2621    0
392     0
1327    1
       ..
3051    0
1730    1
4086    0
2259    0
2920    0
Name: Churn, Length: 5625, dtype: int64

In [38]:
model=keras.Sequential([
    keras.layers.Dense(26, input_shape=(26,), activation='relu'),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=200)

WARNING:tensorflow:From C:\Users\Vikrant Chauhan\anaconda3\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\Vikrant Chauhan\anaconda3\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Epoch 1/200
WARNING:tensorflow:From C:\Users\Vikrant Chauhan\anaconda3\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\Vikrant Chauhan\anaconda3\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

176/176 [==============================] - 4s 5ms/step - loss: 1.6198 - accuracy: 0.7100
Epoch 2/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5211 - accuracy: 0.7698
Epoch 3/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5470 - accuracy: 0.7568
Epoch 4/200
176/176 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7682
Epoch 5/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5283 - accuracy: 0.7760
Epoch 6/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5091 - accuracy: 0.7785
Epoch 7/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5095 - accuracy: 0.7780
Epoch 8/200
176/176 [==============================] - 1s 5ms/step - loss: 0.5006 - accuracy: 0.7792
Epoch 9/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4832 - accuracy: 0.7787
Epoch 10/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4553 - accuracy: 0.7783
Epoch 11/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4613 - accuracy: 0.7813
Epoch 12/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4569 - accuracy: 0.7849
Epoch 13/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4756 - accuracy: 0.7819
Epoch 14/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4794 - accuracy: 0.7835
Epoch 15/200
176/176 [==============================] - 2112s 12s/step - loss: 0.4576 - accuracy: 0.7842
Epoch 16/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4558 - accuracy: 0.7867
Epoch 17/200
176/176 [==============================] - 1s 3ms/step - loss: 0.4564 - accuracy: 0.7876
Epoch 18/200
176/176 [==============================] - 1s 3ms/step - loss: 0.4562 - accuracy: 0.7899
Epoch 19/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4621 - accuracy: 0.7920
Epoch 20/200
176/176 [==============================] - 1s 3ms/step - loss: 0.4535 - accuracy: 0.7893
Epoch 21/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4459 - accuracy: 0.7943
Epoch 22/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4440 - accuracy: 0.7920
Epoch 23/200
176/176 [==============================] - 0s 1ms/step - loss: 0.4568 - accuracy: 0.7920
Epoch 24/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4497 - accuracy: 0.7915
Epoch 25/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4476 - accuracy: 0.7893
Epoch 26/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4535 - accuracy: 0.7913
Epoch 27/200
176/176 [==============================] - 0s 2ms/step - loss: 0.4527 - accuracy: 0.7916
Epoch 28/200
176/176 [==============================] - 0s 1ms/step - loss: 0.4516 - accuracy: 0.7938
Epoch 29/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4479 - accuracy: 0.7915
Epoch 30/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4372 - accuracy: 0.7996
Epoch 31/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7977
Epoch 32/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7954
Epoch 33/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4400 - accuracy: 0.7963
Epoch 34/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4398 - accuracy: 0.7984
Epoch 35/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7911
Epoch 36/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7900
Epoch 37/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7957
Epoch 38/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7943
Epoch 39/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.8000
Epoch 40/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4340 - accuracy: 0.8005
Epoch 41/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4335 - accuracy: 0.8025
Epoch 42/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.8032
Epoch 43/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4382 - accuracy: 0.8007
Epoch 44/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.8011
Epoch 45/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.8014
Epoch 46/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4368 - accuracy: 0.8037
Epoch 47/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4352 - accuracy: 0.8021
Epoch 48/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4427 - accuracy: 0.7959
Epoch 49/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4311 - accuracy: 0.8032
Epoch 50/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4286 - accuracy: 0.8023
Epoch 51/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4386 - accuracy: 0.7977
Epoch 52/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4323 - accuracy: 0.8014
Epoch 53/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4316 - accuracy: 0.8030
Epoch 54/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4285 - accuracy: 0.8002
Epoch 55/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4273 - accuracy: 0.8059
Epoch 56/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4322 - accuracy: 0.8025
Epoch 57/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4301 - accuracy: 0.8037
Epoch 58/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4335 - accuracy: 0.8020
Epoch 59/200
176/176 [==============================] - 1s 6ms/step - loss: 0.4286 - accuracy: 0.7995
Epoch 60/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4313 - accuracy: 0.7989
Epoch 61/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4310 - accuracy: 0.8037
Epoch 62/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8018
Epoch 63/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4310 - accuracy: 0.7996
Epoch 64/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8027
Epoch 65/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4319 - accuracy: 0.8012
Epoch 66/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8044
Epoch 67/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4262 - accuracy: 0.8002
Epoch 68/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4304 - accuracy: 0.8023
Epoch 69/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4292 - accuracy: 0.8011
Epoch 70/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4234 - accuracy: 0.8046
Epoch 71/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4210 - accuracy: 0.8020
Epoch 72/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4223 - accuracy: 0.8027
Epoch 73/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4250 - accuracy: 0.8034
Epoch 74/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4242 - accuracy: 0.8023
Epoch 75/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4250 - accuracy: 0.8021
Epoch 76/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4294 - accuracy: 0.8012
Epoch 77/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4229 - accuracy: 0.8041
Epoch 78/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4274 - accuracy: 0.7989
Epoch 79/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4232 - accuracy: 0.8052
Epoch 80/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4208 - accuracy: 0.8027
Epoch 81/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4192 - accuracy: 0.8062
Epoch 82/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4134 - accuracy: 0.8075
Epoch 83/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4171 - accuracy: 0.8012
Epoch 84/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4179 - accuracy: 0.8039
Epoch 85/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4192 - accuracy: 0.8062
Epoch 86/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4172 - accuracy: 0.8048
Epoch 87/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4278 - accuracy: 0.7979
Epoch 88/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4194 - accuracy: 0.8030
Epoch 89/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4209 - accuracy: 0.7996
Epoch 90/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4169 - accuracy: 0.8050
Epoch 91/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4137 - accuracy: 0.8071
Epoch 92/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4171 - accuracy: 0.8039
Epoch 93/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4164 - accuracy: 0.8059
Epoch 94/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4201 - accuracy: 0.8023
Epoch 95/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4195 - accuracy: 0.8053
Epoch 96/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4191 - accuracy: 0.8018
Epoch 97/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4194 - accuracy: 0.8023
Epoch 98/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4156 - accuracy: 0.8071
Epoch 99/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4182 - accuracy: 0.8037
Epoch 100/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4166 - accuracy: 0.8025
Epoch 101/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4132 - accuracy: 0.8053
Epoch 102/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4199 - accuracy: 0.8034
Epoch 103/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4132 - accuracy: 0.8039
Epoch 104/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4158 - accuracy: 0.8037
Epoch 105/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4179 - accuracy: 0.8014
Epoch 106/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4167 - accuracy: 0.8037
Epoch 107/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4181 - accuracy: 0.8069
Epoch 108/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4134 - accuracy: 0.8060
Epoch 109/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4154 - accuracy: 0.8043
Epoch 110/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4156 - accuracy: 0.8053
Epoch 111/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4183 - accuracy: 0.8048
Epoch 112/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4101 - accuracy: 0.8069
Epoch 113/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4138 - accuracy: 0.8059
Epoch 114/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4158 - accuracy: 0.8036
Epoch 115/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4167 - accuracy: 0.8027
Epoch 116/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4166 - accuracy: 0.8078
Epoch 117/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4141 - accuracy: 0.8066
Epoch 118/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4094 - accuracy: 0.8064
Epoch 119/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4115 - accuracy: 0.8080
Epoch 120/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4156 - accuracy: 0.8059
Epoch 121/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4124 - accuracy: 0.8071
Epoch 122/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4119 - accuracy: 0.8071
Epoch 123/200
176/176 [==============================] - 1s 4ms/step - loss: 0.4130 - accuracy: 0.8078
Epoch 124/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4146 - accuracy: 0.8078
Epoch 125/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4148 - accuracy: 0.8076
Epoch 126/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4150 - accuracy: 0.8057
Epoch 127/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4132 - accuracy: 0.8068
Epoch 128/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4130 - accuracy: 0.8060
Epoch 129/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4100 - accuracy: 0.8092
Epoch 130/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4104 - accuracy: 0.8043
Epoch 131/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4117 - accuracy: 0.8103
Epoch 132/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4141 - accuracy: 0.8085
Epoch 133/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4186 - accuracy: 0.8048
Epoch 134/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4131 - accuracy: 0.8068
Epoch 135/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4129 - accuracy: 0.8103
Epoch 136/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4096 - accuracy: 0.8101
Epoch 137/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4106 - accuracy: 0.8114
Epoch 138/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4102 - accuracy: 0.8052
Epoch 139/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4175 - accuracy: 0.8071
Epoch 140/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4145 - accuracy: 0.8066
Epoch 141/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4115 - accuracy: 0.8060
Epoch 142/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4105 - accuracy: 0.8053
Epoch 143/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4076 - accuracy: 0.8119
Epoch 144/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4122 - accuracy: 0.8076
Epoch 145/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4121 - accuracy: 0.8087
Epoch 146/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4073 - accuracy: 0.8078
Epoch 147/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4114 - accuracy: 0.8103
Epoch 148/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4083 - accuracy: 0.8069
Epoch 149/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4107 - accuracy: 0.8075
Epoch 150/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4083 - accuracy: 0.8071
Epoch 151/200

176/176 [==============================] - 1s 5ms/step - loss: 0.4078 - accuracy: 0.8103
Epoch 152/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4143 - accuracy: 0.8062
Epoch 153/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4109 - accuracy: 0.8103
Epoch 154/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4093 - accuracy: 0.8107
Epoch 155/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4101 - accuracy: 0.8075
Epoch 156/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4106 - accuracy: 0.8094
Epoch 157/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4086 - accuracy: 0.8087
Epoch 158/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4096 - accuracy: 0.8116
Epoch 159/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4127 - accuracy: 0.8100
Epoch 160/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4070 - accuracy: 0.8075
Epoch 161/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4098 - accuracy: 0.8089
Epoch 162/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4070 - accuracy: 0.8096
Epoch 163/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4055 - accuracy: 0.8084
Epoch 164/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4066 - accuracy: 0.8094
Epoch 165/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4081 - accuracy: 0.8096
Epoch 166/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4124 - accuracy: 0.8043
Epoch 167/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4064 - accuracy: 0.8100
Epoch 168/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4059 - accuracy: 0.8119
Epoch 169/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4096 - accuracy: 0.8089
Epoch 170/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4059 - accuracy: 0.8089
Epoch 171/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4116 - accuracy: 0.8064
Epoch 172/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4113 - accuracy: 0.8073
Epoch 173/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4063 - accuracy: 0.8107
Epoch 174/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4058 - accuracy: 0.8107
Epoch 175/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4102 - accuracy: 0.8082
Epoch 176/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4082 - accuracy: 0.8110
Epoch 177/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4087 - accuracy: 0.8087
Epoch 178/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4116 - accuracy: 0.8091
Epoch 179/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4066 - accuracy: 0.8092
Epoch 180/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4054 - accuracy: 0.8087
Epoch 181/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4062 - accuracy: 0.8089
Epoch 182/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4062 - accuracy: 0.8094
Epoch 183/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4066 - accuracy: 0.8100
Epoch 184/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4077 - accuracy: 0.8098
Epoch 185/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4072 - accuracy: 0.8100
Epoch 186/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4090 - accuracy: 0.8060
Epoch 187/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4056 - accuracy: 0.8103
Epoch 188/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4079 - accuracy: 0.8107
Epoch 189/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4070 - accuracy: 0.8124
Epoch 190/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4026 - accuracy: 0.8089
Epoch 191/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4039 - accuracy: 0.8128
Epoch 192/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4093 - accuracy: 0.8084
Epoch 193/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4059 - accuracy: 0.8092
Epoch 194/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4084 - accuracy: 0.8096
Epoch 195/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4041 - accuracy: 0.8085
Epoch 196/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4046 - accuracy: 0.8124
Epoch 197/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4135 - accuracy: 0.8084
Epoch 198/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4075 - accuracy: 0.8108
Epoch 199/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4054 - accuracy: 0.8089
Epoch 200/200
176/176 [==============================] - 1s 5ms/step - loss: 0.4026 - accuracy: 0.8101

In [39]:
model.evaluate(X_test, y_test)

44/44 [==============================] - 1s 5ms/step - loss: 0.4463 - accuracy: 0.7825

[0.44625595211982727, 0.7825160026550293]

In [40]:
def predict(x):
    return 1 if x>=0.5 else 0

In [41]:
yp=model.predict(X_test)

44/44 [==============================] - 1s 4ms/step

In [42]:
yp

array([[0.20109642],
       [0.2929691 ],
       [0.04248082],
       ...,
       [0.84391284],
       [0.64878094],
       [0.5538163 ]], dtype=float32)

In [43]:
y_predict=[]
for temp in yp:
    y_predict.append(predict(temp))

In [44]:
y_predict[0:10]

[0, 0, 0, 1, 0, 1, 0, 0, 0, 0]

In [45]:
y_test[0:10]

2660    0
744     0
5579    1
64      1
3287    1
816     1
2670    0
5920    0
1023    0
6087    0
Name: Churn, dtype: int64

In [46]:
# import seaborn as sn
# cm = tf.math.confusion_matrix(labels=y_test,predictions=y_predict)

# plt.figure(figsize = (10,7))
# sn.heatmap(cm, annot=True, fmt='d')
# plt.xlabel('Predicted')
# plt.ylabel('Truth')